helm:
  versions: v3
git:
  ssh:
    secretName: flux-git-deploy
configureRepositories:
  enable: true
  repositories:
    - name: stable
      url: https://kubernetes-charts.storage.googleapis.com
    - name: incubator
      url: https://kubernetes-charts-incubator.storage.googleapis.com
